"""Add user_id to listings table

Revision ID: 117ba5e74360
Revises: 058deccb83c4
Create Date: 2025-05-06 16:00:31.542884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117ba5e74360'
down_revision: Union[str, None] = '058deccb83c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_listings', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'property_listings', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_listings', type_='foreignkey')
    op.drop_column('property_listings', 'user_id')
    # ### end Alembic commands ###
