"""Description of changes

Revision ID: 53c86bf5005b
Revises: 8b6a51a3323b
Create Date: 2025-05-22 00:59:50.595477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c86bf5005b'
down_revision: Union[str, None] = '8b6a51a3323b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_address_id', 'property_listings', type_='unique')
    op.drop_constraint('unique_property_listing_constraint', 'property_listings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_property_listing_constraint', 'property_listings', ['address_id', 'price', 'sale_status'])
    op.create_unique_constraint('unique_address_id', 'property_listings', ['address_id'])
    # ### end Alembic commands ###
