"""Add fairness_score_updated_at column

Revision ID: 645502b42da3
Revises: 705f255a3052
Create Date: 2025-04-29 14:52:39.684574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645502b42da3'
down_revision: Union[str, None] = '705f255a3052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_listings', sa.Column('fairness_rating_updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('unique_address_id', 'property_listings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_address_id', 'property_listings', ['address_id'])
    op.drop_column('property_listings', 'fairness_rating_updated_at')
    # ### end Alembic commands ###
