"""Add celery tables

Revision ID: 6aa56c5baad6
Revises: 
Create Date: 2025-03-30 19:59:42.618614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa56c5baad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_adress_constraint', 'address', type_='unique')
    op.drop_constraint('unique_property_listing_constraint', 'property_listings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_property_listing_constraint', 'property_listings', ['address_id', 'price', 'sale_status'])
    op.create_unique_constraint('unique_adress_constraint', 'address', ['country', 'administrative_area', 'sub_administrative_area', 'locality', 'postal_code', 'street', 'premise', 'sub_premise'])
    # ### end Alembic commands ###
