"""Change favorites table to use auth_id

Revision ID: 6d0528fcea01
Revises: 6aa56c5baad6
Create Date: 2025-04-21 22:21:33.472294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0528fcea01'
down_revision: Union[str, None] = '6aa56c5baad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_address_constraint', 'address', type_='unique')
    op.create_unique_constraint('unique_adress_constraint', 'address', ['country', 'administrative_area', 'sub_administrative_area', 'locality', 'postal_code', 'street', 'premise', 'sub_premise'])
    op.add_column('favorites', sa.Column('auth_id', sa.String(length=255), nullable=False))
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['auth_id'], ['auth_id'])
    op.drop_column('favorites', 'user_id')
    op.drop_constraint('unique_property_listing_constraint', 'property_listings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_property_listing_constraint', 'property_listings', ['address_id', 'price', 'sale_status'])
    op.add_column('favorites', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'users', ['user_id'], ['id'])
    op.drop_column('favorites', 'auth_id')
    op.drop_constraint('unique_adress_constraint', 'address', type_='unique')
    op.create_unique_constraint('unique_address_constraint', 'address', ['country', 'administrative_area', 'sub_administrative_area', 'locality', 'postal_code', 'street', 'premise', 'sub_premise'])
    # ### end Alembic commands ###
