"""Add fairness_rating to listing

Revision ID: 705f255a3052
Revises: bd6c032eb0d0
Create Date: 2025-04-22 12:03:10.349398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '705f255a3052'
down_revision: Union[str, None] = 'bd6c032eb0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_listings', sa.Column('fairness_rating', postgresql.ENUM('fraud', 'bad', 'fair', 'good', name='fairness_rating_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_listings', 'fairness_rating')
    # ### end Alembic commands ###
