"""Update delete on cascade relationships

Revision ID: 8b6a51a3323b
Revises: 257d5c5ac354
Create Date: 2025-05-12 19:05:48.872203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6a51a3323b'
down_revision: Union[str, None] = '257d5c5ac354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_listing_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'property_listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('unique_property_listing', 'property_listings', type_='unique')
    op.drop_constraint('property_listings_user_id_fkey', 'property_listings', type_='foreignkey')
    op.create_foreign_key(None, 'property_listings', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_listings', type_='foreignkey')
    op.create_foreign_key('property_listings_user_id_fkey', 'property_listings', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint('unique_property_listing', 'property_listings', ['address_id', 'price', 'sale_status'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_listing_id_fkey', 'favorites', 'property_listings', ['listing_id'], ['id'])
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
