"""Fix typo

Revision ID: a623761502bf
Revises: 645502b42da3
Create Date: 2025-04-29 16:39:02.046859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a623761502bf'
down_revision: Union[str, None] = '645502b42da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_property_listing_constraint', 'property_listings', ['address_id', 'price', 'sale_status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_property_listing_constraint', 'property_listings', type_='unique')
    # ### end Alembic commands ###
