"""Unique address id

Revision ID: f050d86bf659
Revises: 705f255a3052
Create Date: 2025-04-29 12:02:24.337807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f050d86bf659'
down_revision: Union[str, None] = '705f255a3052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_listings', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('unique_property_listing_constraint', 'property_listings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_property_listing_constraint', 'property_listings', ['address_id', 'price', 'sale_status'])
    op.alter_column('property_listings', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
