"""Add unique constraints for address and property_listings

Revision ID: a63f603a125f
Revises: 2adb9fb0d684
Create Date: 2025-03-25 13:29:53.146841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63f603a125f'
down_revision: Union[str, None] = '2adb9fb0d684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_address_constraint', 'address', type_='unique')
    op.create_unique_constraint('unique_adress_constraint', 'address', ['country', 'administrative_area', 'sub_administrative_area', 'locality', 'postal_code', 'street', 'premise', 'sub_premise'])
    op.drop_constraint('unique_property_listing_constraint', 'property_listings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_property_listing_constraint', 'property_listings', ['address_id', 'price', 'sale_status'])
    op.drop_constraint('unique_adress_constraint', 'address', type_='unique')
    op.create_unique_constraint('unique_address_constraint', 'address', ['country', 'administrative_area', 'sub_administrative_area', 'locality', 'postal_code', 'street', 'premise', 'sub_premise'])
    # ### end Alembic commands ###
