"""Fix test table relationships

Revision ID: f95f23377985
Revises: 7379cfe86b0d
Create Date: 2025-03-20 17:18:10.736872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95f23377985'
down_revision: Union[str, None] = '7379cfe86b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_listing_test_table_address_id_fkey1', 'property_listing_test_table', type_='foreignkey')
    op.create_foreign_key(None, 'property_listing_test_table', 'address_test_table', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_listing_test_table', type_='foreignkey')
    op.create_foreign_key('property_listing_test_table_address_id_fkey1', 'property_listing_test_table', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###
